### ISSUE TITLE
[Bug] ShowCoordinatePoints Error

### ISSUE THREAD

**Issue by ingalls** [JamesLMilner/terra-draw#520]
**Describe the bug**

- Call `draw.start()`
- Call `draw.setMode('select')`
- Call `draw.addFeatures()` with the given feature to edit
- Call `draw.selectFeature(id)`
- After editing call `draw.removeFeatures()`
-` draw.setMode('static')`
- `draw.stop()`

The first time this process runs, editing will work as expected however if the above is repeated on the same feature ID, the process will fail with the error below. If a feature with a different ID is edited, editing will work as expected.

This behavior is resolved if `showCoordinatePoints: false` is used.

**Terra Draw npm version**
1.4.0

**Expected behavior**

If `showCoordinatePoints: true` is set on the PolygonMode, editing the feature should be possible multiple times

```
Uncaught (in promise) Error: No feature with this id (13568bee-c594-41b6-a0e9-5b73981f75ab), can not get geometry copy
    getGeometryCopy store.ts:202
    n2 coordinate-point.behavior.ts:38
    createOrUpdate coordinate-point.behavior.ts:37
    afterFeatureAdded polygon.mode.ts:1157
    addFeatures terra-draw.ts:667
    o2 store.ts:169
    load store.ts:109
    addFeatures terra-draw.ts:622
    editGeometry map.ts:881
    wrappedAction pinia.mjs:1379
    actionName pinia.mjs:932
    handleRadial Map.vue:728
    20 Map.vue:412
    callWithErrorHandling runtime-core.esm-bundler.js:199
    callWithAsyncErrorHandling runtime-core.esm-bundler.js:206
    emit runtime-core.esm-bundler.js:6386
    onClick RadialMenu.vue:167
    handleClick RadialMenu.js:132
    createMenu RadialMenu.js:219
    createMenu RadialMenu.js:215
    open RadialMenu.js:46
    mounted RadialMenu.vue:170
    promise callback*nextTick runtime-core.esm-bundler.js:289
    mounted RadialMenu.vue:160
    createHook runtime-core.esm-bundler.js:2815
    callWithErrorHandling runtime-core.esm-bundler.js:199
    callWithAsyncErrorHandling runtime-core.esm-bundler.js:206
    __weh runtime-core.esm-bundler.js:2795
    flushPostFlushCbs runtime-core.esm-bundler.js:385
    flushJobs runtime-core.esm-bundler.js:427
    promise callback*queueFlush runtime-core.esm-bundler.js:322
    queueJob runtime-core.esm-bundler.js:317
    scheduler runtime-core.esm-bundler.js:5448
    trigger reactivity.esm-bundler.js:253
    endBatch reactivity.esm-bundler.js:311
    trigger reactivity.esm-bundler.js:724
    set reactivity.esm-bundler.js:1007
    initOverlays map.ts:450
    fire evented.ts:132
    click map_event.ts:45
    handleEvent handler_manager.ts:392
    addEventListener dom.ts:62
    xa handler_manager.ts:212
    <anonymous> map.ts:709
    init map.ts:386
[store.ts:202:9](http://localhost:8080/node_modules/terra-draw/src/store/store.ts)
```

**Desktop (please complete the following information):**
 - OS: Ubuntu 24.04
 - Browser Firefox
 - Version: 136

cc/  @JamesLMilner

**Comment by ingalls** [comment]
@JamesLMilner Do you have a sample CodePen or similiar for me to mock this up to make it easier for you?

**Comment by JamesLMilner** [comment]
Hey @ingalls - let me take a look into this! Unfortunately no CodePen/Sandbox to hand. Long term I want to set one up to simplify debugging things like this.

**Comment by JamesLMilner** [comment]
@ingalls I just looked into this and I think this is actually a broader issue with how 'guidance features' (selection points, midpoints, coordinate points etc) are not cleared up when a feature is deleted. `removeFeatures` is actually pretty basic and literally just deletes the specified geometries. I need to figure out a cleaner and more robust way to handle cleaning those geometries up!

**Comment by JamesLMilner** [comment]
Hey @ingalls - I just released `1.4.1` that aims to tackle this, can you check this resolves the problem for you? 👍🏻

**Comment by ingalls** [comment]
Hey @JamesLMilner Thanks a ton for jumping on this. Just gave it a go but unfortunately still seeing a similar behavior

```
Uncaught (in promise) Error: No feature with this id (cae54558-bfd3-4cc1-bc23-f856d2d39fec), can not get geometry copy
    getGeometryCopy store.ts:202
    n2 coordinate-point.behavior.ts:38
    createOrUpdate coordinate-point.behavior.ts:37
    afterFeatureAdded polygon.mode.ts:1157
    addFeatures terra-draw.ts:692
    o2 store.ts:169
    load store.ts:109
    addFeatures terra-draw.ts:647
    editGeometry map.ts:880
    wrappedAction pinia.mjs:1379
    actionName pinia.mjs:932
    handleRadial Map.vue:736
    20 Map.vue:412
    callWithErrorHandling runtime-core.esm-bundler.js:199
    callWithAsyncErrorHandling runtime-core.esm-bundler.js:206
    emit runtime-core.esm-bundler.js:6386
    onClick RadialMenu.vue:167
    handleClick RadialMenu.js:132
    createMenu RadialMenu.js:219
    createMenu RadialMenu.js:215
    open RadialMenu.js:46
    mounted RadialMenu.vue:170
    promise callback*nextTick runtime-core.esm-bundler.js:289
    mounted RadialMenu.vue:160
    createHook runtime-core.esm-bundler.js:2815
    callWithErrorHandling runtime-core.esm-bundler.js:199
    callWithAsyncErrorHandling runtime-core.esm-bundler.js:206
    __weh runtime-core.esm-bundler.js:2795
    flushPostFlushCbs runtime-core.esm-bundler.js:385
    flushJobs runtime-core.esm-bundler.js:427
    promise callback*queueFlush runtime-core.esm-bundler.js:322
    queueJob runtime-core.esm-bundler.js:317
    scheduler runtime-core.esm-bundler.js:5448
    trigger reactivity.esm-bundler.js:253
    endBatch reactivity.esm-bundler.js:311
    trigger reactivity.esm-bundler.js:724
    set reactivity.esm-bundler.js:1007
    initOverlays map.ts:453
    fire evented.ts:132
    click map_event.ts:45
    handleEvent handler_manager.ts:392
```

**Comment by JamesLMilner** [comment]
Hey @ingalls can you try with 1.4.2 - I reproduced the same error and was able to fix it (hopefully!)

**Comment by ingalls** [comment]
@JamesLMilner You're the best thanks!! Looking good on my end, I'll close this ticket!
